// Trader shorthand for riven stats, keyed by the game's upgrade tag. The tags are
// the ones a decoded riven carries (config/shared/wfmRivenVocabulary.ts lists
// them all); a tag missing here simply has no code.

export const RIVEN_STAT_CODES: Readonly<Record<string, readonly string[]>> = {
  WeaponCritChanceMod: ["cc"],
  WeaponCritDamageMod: ["cd"],
  WeaponFireIterationsMod: ["ms"],
  WeaponFireRateMod: ["fr", "as"],
  WeaponDamageAmountMod: ["dmg"],
  WeaponMeleeDamageMod: ["dmg"],
  WeaponReloadSpeedMod: ["rls"],
  WeaponStunChanceMod: ["sc"],
  WeaponProcTimeMod: ["sd"],
  WeaponPunctureDepthMod: ["pt"],
  WeaponClipMaxMod: ["mag"],
  WeaponAmmoMaxMod: ["ammo"],
  WeaponRecoilReductionMod: ["rec"],
  WeaponZoomFovMod: ["zoom", "z"],
  WeaponProjectileSpeedMod: ["pfs"],
  WeaponImpactDamageMod: ["imp"],
  WeaponArmorPiercingDamageMod: ["punc"],
  WeaponSlashDamageMod: ["sl"],
  WeaponFreezeDamageMod: ["cold"],
  WeaponFireDamageMod: ["heat"],
  WeaponElectricityDamageMod: ["elec"],
  WeaponToxinDamageMod: ["tox"],
  WeaponFactionDamageGrineer: ["dtg"],
  WeaponFactionDamageCorpus: ["dtc"],
  WeaponFactionDamageInfested: ["dti"],
  WeaponMeleeFactionDamageGrineer: ["dtg"],
  WeaponMeleeFactionDamageCorpus: ["dtc"],
  WeaponMeleeFactionDamageInfested: ["dti"],
  WeaponMeleeRangeIncMod: ["rng"],
  ComboDurationMod: ["combo"],
  SlideAttackCritChanceMod: ["slide"],
  WeaponMeleeFinisherDamageMod: ["fin"],
  WeaponMeleeComboEfficiencyMod: ["eff"],
  WeaponMeleeComboInitialBonusMod: ["ic"],
  WeaponMeleeComboBonusOnHitMod: ["ccc"],
};
